import * as React from "react";
import type { AuditEngineResult } from "@/lib/audit-engine";

interface AuditReportEmailProps {
  auditId: string;
  result: AuditEngineResult;
  company?: string;
  reportUrl: string;
}

export const AuditReportEmail = ({
  auditId,
  result,
  company,
  reportUrl,
}: AuditReportEmailProps) => {
  const isHighSavings = result.estimatedMonthlySavingsUsd > 500;

  return (
    <div style={containerStyle}>
      <div style={headerStyle}>
        <div style={logoContainerStyle}>
          <div style={logoStyle}></div>
          <span style={logoTextStyle}>Aethra</span>
        </div>
      </div>

      <div style={contentStyle}>
        <h1 style={h1Style}>Your AI Spend Optimization Report</h1>
        <p style={pStyle}>
          Hello {company ? `Team ${company}` : "there"},
        </p>
        <p style={pStyle}>
          We've completed our analysis of your AI tool stack. Below is a summary of our findings and potential optimizations.
        </p>

        <div style={kpiGridStyle}>
          <div style={kpiCardStyle}>
            <div style={kpiLabelStyle}>Monthly Spend</div>
            <div style={kpiValueStyle}>${result.totalMonthlySpendUsd.toFixed(2)}</div>
          </div>
          <div style={kpiCardStyle}>
            <div style={kpiLabelStyle}>Est. Savings</div>
            <div style={{ ...kpiValueStyle, color: "#10b981" }}>
              ${result.estimatedMonthlySavingsUsd.toFixed(2)}
            </div>
          </div>
        </div>

        <div style={summaryBoxStyle}>
          <h2 style={h2Style}>Executive Summary</h2>
          <p style={{ ...pStyle, fontSize: "14px", lineHeight: "1.6" }}>
            {result.personalizedSummary}
          </p>
        </div>

        <div style={ctaContainerStyle}>
          <a href={reportUrl} style={buttonStyle}>
            View Interactive Report
          </a>
        </div>

        {isHighSavings && (
          <div style={credexStyle}>
            <h3 style={{ ...h3Style, color: "#8b5cf6" }}>Maximize your savings with Credex</h3>
            <p style={{ ...pStyle, fontSize: "13px" }}>
              Based on your optimization potential of ${result.estimatedMonthlySavingsUsd.toFixed(2)}/mo, we recommend a personalized consultation with the Credex team to unlock enterprise-grade licensing and consolidated billing.
            </p>
            <a href="https://credex.ai/consultation" style={secondaryButtonStyle}>
              Book a Credex Consultation
            </a>
          </div>
        )}

        <hr style={hrStyle} />

        <p style={footerTextStyle}>
          Audit ID: {auditId}<br />
          Generated by Aethra AI Spend Auditor.
        </p>
      </div>
    </div>
  );
};

// Styles (Inline for email compatibility)
const containerStyle: React.CSSProperties = {
  fontFamily: "system-ui, -apple-system, sans-serif",
  backgroundColor: "#f9fafb",
  padding: "40px 20px",
  color: "#111827",
};

const headerStyle: React.CSSProperties = {
  maxWidth: "600px",
  margin: "0 auto 20px",
  textAlign: "center",
};

const logoContainerStyle: React.CSSProperties = {
  display: "inline-flex",
  alignItems: "center",
  gap: "10px",
};

const logoStyle: React.CSSProperties = {
  width: "24px",
  height: "24px",
  backgroundColor: "#8b5cf6",
  borderRadius: "4px",
};

const logoTextStyle: React.CSSProperties = {
  fontSize: "20px",
  fontWeight: "bold",
  color: "#111827",
};

const contentStyle: React.CSSProperties = {
  maxWidth: "600px",
  margin: "0 auto",
  backgroundColor: "#ffffff",
  borderRadius: "12px",
  padding: "40px",
  boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
};

const h1Style: React.CSSProperties = {
  fontSize: "24px",
  fontWeight: "800",
  marginBottom: "24px",
  textAlign: "center",
  letterSpacing: "-0.025em",
};

const h2Style: React.CSSProperties = {
  fontSize: "18px",
  fontWeight: "700",
  marginBottom: "12px",
};

const h3Style: React.CSSProperties = {
  fontSize: "16px",
  fontWeight: "600",
  marginBottom: "8px",
};

const pStyle: React.CSSProperties = {
  fontSize: "16px",
  color: "#4b5563",
  lineHeight: "1.5",
  marginBottom: "16px",
};

const kpiGridStyle: React.CSSProperties = {
  display: "table",
  width: "100%",
  marginBottom: "32px",
};

const kpiCardStyle: React.CSSProperties = {
  display: "table-cell",
  width: "50%",
  padding: "20px",
  textAlign: "center",
  backgroundColor: "#f3f4f6",
  borderRadius: "8px",
};

const kpiLabelStyle: React.CSSProperties = {
  fontSize: "12px",
  fontWeight: "600",
  color: "#6b7280",
  textTransform: "uppercase",
  marginBottom: "4px",
};

const kpiValueStyle: React.CSSProperties = {
  fontSize: "24px",
  fontWeight: "bold",
};

const summaryBoxStyle: React.CSSProperties = {
  backgroundColor: "#f5f3ff",
  border: "1px solid #ddd6fe",
  borderRadius: "8px",
  padding: "20px",
  marginBottom: "32px",
};

const ctaContainerStyle: React.CSSProperties = {
  textAlign: "center",
  marginBottom: "32px",
};

const buttonStyle: React.CSSProperties = {
  display: "inline-block",
  backgroundColor: "#8b5cf6",
  color: "#ffffff",
  padding: "14px 28px",
  borderRadius: "8px",
  fontWeight: "bold",
  textDecoration: "none",
};

const credexStyle: React.CSSProperties = {
  padding: "24px",
  border: "2px dashed #ddd6fe",
  borderRadius: "12px",
  backgroundColor: "#ffffff",
  marginBottom: "32px",
};

const secondaryButtonStyle: React.CSSProperties = {
  display: "inline-block",
  color: "#8b5cf6",
  fontWeight: "600",
  textDecoration: "underline",
};

const hrStyle: React.CSSProperties = {
  border: "0",
  borderTop: "1px solid #e5e7eb",
  margin: "32px 0",
};

const footerTextStyle: React.CSSProperties = {
  fontSize: "12px",
  color: "#9ca3af",
  textAlign: "center",
};
